<?php

declare(strict_types=1);

// ZEF Framework v2.20.0 — Application layer (OpenAPI documentation module)

namespace Zef\Framework\OpenApi;

use Zef\Framework\Validation\Validator;

/**
 * Core schema-generation engine: maps PHP types, DTO classes, attributes,
 * backed enums and the v2.8.0 validation engine onto OpenAPI Schema
 * Objects.
 *
 * Circular references (a DTO referencing itself transitively) resolve to
 * $ref placeholders under #/components/schemas/<name>, so recursive tree
 * structures document cleanly instead of recursing forever.
 *
 * Since the sonar-zero campaign the reflection/type mapping lives in
 * TypeSchemaMapper, class/enum/attribute assembly in ClassSchemaBuilder,
 * and the validator-derived constraints in FieldRulesSchemaMapper.
 */
final class SchemaGenerator
{
    /** @var array<string, Schema> */
    private array $cache = [];

    /** @var array<string, true> class-strings currently being expanded */
    private array $inProgress = [];

    private ?TypeSchemaMapper $typeMapper = null;

    private ?ClassSchemaBuilder $builder = null;

    private ?FieldRulesSchemaMapper $fieldRulesMapper = null;

    /**
     * Generate the schema for a DTO class. Consults
     * SchemaDefinitionInterface first, then backed/unit enums, then
     * reflection over #[Schema]/#[Property] attributes and native types.
     */
    public function generateFromClass(string $className): Schema
    {
        if (!class_exists($className) && !enum_exists($className)) {
            throw new SchemaDefinitionException(
                "Schema generation target '{$className}' is not an existing class or enum.",
            );
        }

        if (isset($this->cache[$className])) {
            return $this->cache[$className];
        }

        if (isset($this->inProgress[$className])) {
            return new Schema(ref: $this->schemaRef($className));
        }

        $this->inProgress[$className] = true;

        try {
            $schema = $this->builder()->build($className);
        } finally {
            unset($this->inProgress[$className]);
        }

        $this->cache[$className] = $schema;

        return $schema;
    }

    /**
     * Map an arbitrary reflection type (property/parameter/return) to a
     * schema. Union types become oneOf (nullable unions collapse into a
     * nullable base); intersection types become allOf; plain arrays emit
     * an unconstrained map as items.
     */
    public function generateFromType(\ReflectionType $type): Schema
    {
        return $this->typeMapper()->map($type);
    }

    /**
     * Derive an object schema from the v2.8.0 validation engine: every
     * declared field becomes a property with constraints inferred from the
     * registered rule chain, plus the required/nullable bookkeeping.
     */
    public function generateFromValidator(Validator $validator): Schema
    {
        return $this->fieldRulesMapper()->mapValidator($validator);
    }

    /**
     * Component-name keyed view of every class schema generated by this
     * instance — ready to feed SpecificationBuilder::addSchema(). Schemas
     * produced from validators (not classes) are not included.
     *
     * @return array<string, Schema>
     */
    public function registeredSchemas(): array
    {
        $out = [];

        foreach ($this->cache as $className => $schema) {
            $out[$this->schemaNameFor($className)] = $schema;
        }

        ksort($out, SORT_STRING);

        return $out;
    }

    /** Component reference key for a class (#[Schema(name)] or short name). */
    public function schemaNameFor(string $className): string
    {
        if (class_exists($className) || enum_exists($className)) {
            return $this->declaredSchemaName($className);
        }

        return $className;
    }

    /**
     * @internal component $ref for a generated class schema; used by the
     * mapping collaborators that resolve class references
     */
    public function schemaRef(string $className): string
    {
        return '#/components/schemas/' . $this->schemaNameFor($className);
    }

    private function declaredSchemaName(string $className): string
    {
        // @phpstan-ignore argument.type (guarded by class_exists || enum_exists in schemaNameFor)
        $reflection = new \ReflectionClass($className);
        $attribute = $reflection->getAttributes(
            Attribute\Schema::class,
            \ReflectionAttribute::IS_INSTANCEOF,
        )[0] ?? null;
        $declared = $attribute !== null ? $attribute->newInstance()->name : null;

        if (is_string($declared) && trim($declared) !== '') {
            return $declared;
        }

        if (is_a($className, SchemaDefinitionInterface::class, true)) {
            // @var string $declared
            return $className::openApiSchemaName();
        }

        return $reflection->getShortName();
    }

    private function typeMapper(): TypeSchemaMapper
    {
        return $this->typeMapper ??= new TypeSchemaMapper($this);
    }

    private function builder(): ClassSchemaBuilder
    {
        return $this->builder ??= new ClassSchemaBuilder($this);
    }

    private function fieldRulesMapper(): FieldRulesSchemaMapper
    {
        return $this->fieldRulesMapper ??= new FieldRulesSchemaMapper();
    }
}
